#pragma once

#include "pico/stdlib.h"

#define CFG_TUSB_MCU OPT_MCU_RP2040
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUSB_RHPORT1_MODE (OPT_MODE_HOST | OPT_MODE_FULL_SPEED)

#ifndef CFG_TUSB_OS
#define CFG_TUSB_OS OPT_OS_PICO
#endif

#define CFG_TUD_ENABLED 1
#define CFG_TUH_ENABLED 1

#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUH_ENDPOINT0_SIZE 64

#define CFG_TUD_HID 2
#define CFG_TUD_HID_EP_BUFSIZE 16

#define CFG_TUH_HID 4
#define CFG_TUH_HID_EPIN_BUFSIZE 64
#define CFG_TUH_HID_EPOUT_BUFSIZE 64
